import { APAReference } from "../components/pages/references";

export const bibliography: APAReference[] = [
  {
    authors: [
      "Alemohammad, S.",
      "Casco-Rodriguez, J.",
      "Luzi, L.",
      "Humayun, A. I.",
      "Babaei, H.",
      "LeJeune, D.",
      "Siahkoohi, A.",
      "Baraniuk, R. G.",
    ],
    year: "2023",
    title: "Self-Consuming Generative Models Go MAD",
    sourceType: "preprint",
    identifier: "arXiv:2307.01850",
    doi: "10.48550/arXiv.2307.01850",
    url: "https://doi.org/10.48550/arXiv.2307.01850",
  },
  {
    authors: ["ASRG"],
    year: "2025, January 28",
    title: "Sabot in the age of AI",
    sourceType: "webpage",
    containerTitle: "ASRG",
    url: "https://algorithmic-sabotage.github.io/asrg/posts/sabot-in-the-age-of-ai/",
  },
  {
    authors: ["Belanger, A."],
    year: "2025",
    title:
      "AI haters build tarpits to trap and trick AI scrapers that ignore robots.txt",
    sourceType: "webpage",
    url: "https://arstechnica.com/tech-policy/2025/01/ai-haters-build-tarpits-to-trap-and-trick-ai-scrapers-that-ignore-robots-txt/",
  },
  {
    authors: ["Bracken, P. J."],
    year: "2013",
    title:
      "The second nuclear age: Strategy, danger, and the new power politics ",
    sourceType: "journal",
    url: "First St. Martin’s Griffin edition: November 2013). St. Martin’s Griffin",
  },
  {
    authors: [
      "Çam, E.",
      "Hungerford, Z.",
      "Schoch, N.",
      "Francys Pinto Miranda",
      "Carlos David Yáñez de León",
    ],
    year: "2024",
    title: "Electricity 2024",
    sourceType: "report",
    publisher: "International Energy Agency",
    url: "https://www.iea.org/reports/electricity-2024",
  },
  {
    authors: ["McQuillan, D."],
    year: "2025",
    title: "Labour’s AI Action Plan—A gift to the far right",
    sourceType: "webpage",
    containerTitle: "Computer Weekly",
    url: "https://www.computerweekly.com/opinion/Labours-AI-Action-Plan-a-gift-to-the-far-right",
  },
  {
    authors: ["Farías, V.", "Margolis, J.", "Rockmore, T."],
    year: "1991",
    title: "Heidegger and nazism.",
    sourceType: "journal",
    containerTitle: "American Political Science Association",
    url: "https://doi.org/10.2307/2163220",
  },
  {
    authors: ["Heidegger, M."],
    year: "1954",
    title: "The Question Concerning Technology",
    sourceType: "other",
  },
  {
    authors: ["Heikkilä, M."],
    year: "2023",
    title:
      "This new data poisoning tool lets artists ﬁght back against generative AI",
    sourceType: "webpage",
    url: "https://www.technologyreview.com/2023/10/23/1082189/data-poisoning-artists-fight-generative-ai/",
  },
  {
    authors: ["Hendrycks, D.", "Schmidt, E.", "Wang, A."],
    year: "2025",
    title: "Superintelligence Strategy.",
    sourceType: "report",
    url: "https://www.nationalsecurity.ai/",
  },
  {
    authors: ["Illich, I."],
    year: "1973",
    title: "Tools for Conviviality",
    sourceType: "report",
    url: "https://arl.human.cornell.edu/linked%20docs/Illich_Tools_for_Conviviality.pdf",
  },
  {
    authors: ["Geuter, J."],
    year: "2025",
    title: "These are not the same",
    sourceType: "webpage",
    url: "https://tante.cc/2025/04/15/these-are-not-the-same/",
  },
  {
    authors: ["Kristensen, M."],
    year: "2023",
    title: "The Ethics of Ecological Sabotage—Farsight",
    sourceType: "webpage",
  },
  {
    authors: ["Larson, M."],
    year: "2023",
    title:
      "Computer Center Sabotage, 1968–1971: Luddism, Black Studies, and the Diversion of Technological Progress",
    sourceType: "journal",
    containerTitle: "Boundary 2",
    doi: "10.1215/01903659-10694281",
    url: "https://doi.org/10.1215/01903659-10694281",
  },
  {
    authors: ["Li, P.", "Yang, J.", "Islam, M. A.", "Ren, S."],
    year: "2025",
    title:
      "Making AI Less ‘Thirsty’: Uncovering and Addressing the Secret Water Footprint of AI Models",
    sourceType: "preprint",
    identifier: "arXiv:2304.03271",
    doi: "10.48550/arXiv.2304.03271",
    url: "https://doi.org/10.48550/arXiv.2304.03271",
  },
  {
    authors: ["Malm, A."],
    year: "2021",
    title: "How to blow up a pipeline: Learning to fight in a world on fire",
    sourceType: "other",
    publisher: "Verso",
  },
  {
    authors: ["Medina, E."],
    year: "2014",
    title:
      "Cybernetic revolutionaries: Technology and politics in Allende’s Chile",
    sourceType: "other",
    publisher: "MIT Press",
  },
  {
    authors: ["Noble, D. F."],
    year: "2011",
    title: "Forces of production: A social history of industrial automation.",
    sourceType: "other",
    publisher: "Transaction Publishers",
  },
  {
    authors: ["Oxford English Dictionary"],
    year: "2023",
    title: "Sabotage, n.",
    sourceType: "webpage",
    publisher: "Oxford University Press",
    doi: "10.1093/OED/1124179543",
    url: "https://doi.org/10.1093/OED/1124179543",
  },
  {
    authors: ["Phenomenal World"],
    year: "2019",
    title: "Optimizing the Crisis",
    sourceType: "webpage",
    url: "https://www.phenomenalworld.org/interviews/counter-optimizing-the-crisis/",
  },
  {
    authors: ["Sadowski, J."],
    year: "2025",
    title:
      "The Mechanic and the Luddite: A Ruthless Criticism of Technology and Capitalism",
    sourceType: "other",
    publisher: "University of California Press",
  },
  {
    authors: ["Knight, W."],
    year: "2025, February 11",
    title:
      "An Adviser to Elon Musk’s xAI Has a Way to Make AI More Like Donald Trump",
    sourceType: "webpage",
    url: "https://www.wired.com/story/xai-make-ai-more-like-trump/",
  },
  {
    authors: ["Yao, Y.", "Li, H.", "Zheng, H.", "Zhao, B. Y."],
    year: "2019",
    title: "Latent Backdoor Attacks on Deep Neural Networks",
    sourceType: "journal",
    containerTitle:
      "Proceedings of the 2019 ACM SIGSAC Conference on Computer and Communications Security",
    doi: "10.1145/3319535.3354209",
    url: "https://doi.org/10.1145/3319535.3354209",
  },
];
