// src/data/images.ts

import { ImageReference } from "../components/visual/figure-image";

export const images: ImageReference[] = [
  {
    id: "cybersyn",
    src: "https://www.uc.cl/site/assets/files/20037/cyberno_se_que.png",
    alt: "Cybersyn control room",
    title: "Cybersyn's Legacy for Technology and Society. The control room.",
    source:
      "How to Design a Revolution: Unveiling Chilean Design and Industrial Aesthetics in the 70s",
    author: "Pontificia Universidad Católica de Chile",
    year: "2024",
    url: "https://www.uc.cl/noticias/how-to-design-a-revolution-unveiling-chilean-design-and-industrial-aesthetics-in-the-70s/",
    copyrightHolder: "Pontificia Universidad Católica de Chile",
    page: 15,
    figure: 10,
  },
  {
    id: "GoogleMapsHack-1",
    src: "https://www.simonweckert.com/img/googlemapshacks/3.JPG",
    alt: "99 second hand smartphones are transported in a handcart to generate virtual traffic jam in Google Maps",
    title: "Google Maps Hack",
    source: "Google Maps Hacks Performance & Installation, 2020",
    author: "Simon Weckert",
    year: "2020",
    url: "https://www.simonweckert.com/googlemapshacks.html",
    copyrightHolder: "Simon Weckert",
    page: 18,
    figure: 11,
  },
  {
    id: "GoogleMapsHack-2",
    src: "https://www.simonweckert.com/img/googlemapshacks/4.JPG",
    alt: "99 second hand smartphones are transported in a handcart to generate virtual traffic jam in Google Maps",
    title: "Google Maps Hack",
    source: "Google Maps Hacks Performance & Installation, 2020",
    author: "Simon Weckert",
    year: "2020",
    url: "https://www.simonweckert.com/googlemapshacks.html",
    copyrightHolder: "Simon Weckert",
    page: 18,
    figure: 12,
  },
  {
    id: "latentBackdoorTable",
    src: "/images/latent-backdoor-table.svg",
    alt: "Benchmark results of the latent backdoor attack",
    title: "Benchmark results of the latent backdoor attack",
    source: "",
    author: "Yao, Y.",
    year: "2025",
    url: "",
    copyrightHolder: "Yao, Y.",
    page: 25,
    figure: 17,
  },
  {
    id: "woodenShoesCircle",
    src: "/images/Wood_shoes-circle-big-tr.png",
    alt: "Rendering of wooden shoes arranged in a circle",
    title:
      "Rendering of wooden shoes arranged in a circle, based on a GLTF object from 'https://poly.cam'",
    source: "https://poly.cam/capture/c3376fd1-35fd-44cd-8bc7-63f25fc33814",
    author: "Maximilian Schmalenbach & farmerornot",
    year: "2025",
    url: "https://poly.cam/capture/c3376fd1-35fd-44cd-8bc7-63f25fc33814",
    copyrightHolder: "",
    page: 10,
    figure: 8,
  },
  {
    id: "computerPiercedByMotherboard",
    src: "/images/mac-tl1.png",
    alt: "Rendering of a computer pierced by a motherboard",
    title:
      "Rendering of a computer pierced by a motherboard, based on GLTF objects from 'https://poly.cam'",
    source: "https://poly.cam/capture/172f3ebd-0ff7-45cc-83ec-f7e4533b2145",
    author: "Maximilian Schmalenbach & Sigdesign & Ethanol98",
    year: "2025",
    url: "https://poly.cam/capture/172f3ebd-0ff7-45cc-83ec-f7e4533b2145",
    copyrightHolder: "",
    page: 21,
    figure: 13,
  },
  {
    id: "hammer",
    src: "/images/hammer-tl.png",
    alt: "Rendering of a hammer",
    title:
      "Rendering of a hammer, based on a GLTF object from 'https://poly.cam'",
    source: "https://poly.cam/capture/08a9fca4-3c88-48e0-a78a-47a4195cbd91",
    author: "Maximilian Schmalenbach & Pixle",
    year: "2025",
    url: "https://poly.cam/capture/08a9fca4-3c88-48e0-a78a-47a4195cbd91",
    copyrightHolder: "",
    page: 24,
    figure: 16,
  },
  {
    id: "hilti",
    src: "/images/hilti-tl.png",
    alt: "Rendering of a 'Hilti' hammer drill",
    title:
      "Rendering of a 'Hilti' hammer drill, based on a GLTF object from 'https://poly.cam'",
    source: "https://poly.cam/capture/bb61cd28-d1ae-4798-88c9-15a6a4da529e",
    author: "Maximilian Schmalenbach & Pilki",
    year: "2025",
    url: "https://poly.cam/capture/bb61cd28-d1ae-4798-88c9-15a6a4da529e",
    copyrightHolder: "",
    page: 24,
    figure: 14,
  },
  {
    id: "mac",
    src: "/images/mac-tl.png",
    alt: "Rendering of a 'Mac' computer",
    title:
      "Rendering of a 'Mac' computer, based on a GLTF object from 'https://poly.cam'",
    source: "https://poly.cam/capture/a35c6336-55e6-4a9e-9e94-dc71b7eb2316",
    author: "Maximilian Schmalenbach & daviswr",
    year: "2025",
    url: "https://poly.cam/capture/a35c6336-55e6-4a9e-9e94-dc71b7eb2316",
    copyrightHolder: "",
    page: 24,
    figure: 15,
  },
  {
    id: "pipeline",
    src: "/images/pipeline.png",
    alt: "Rendering of a weathered pump, connected to a pipeline",
    title:
      "Rendering of a weathered pump, connected to a pipeline, based on a GLTF object from 'https://poly.cam'",
    source: "https://poly.cam/capture/2917E164-71BC-49A2-B52B-B57EDE41B252?",
    author: "Maximilian Schmalenbach & Chef-Mistro",
    year: "2025",
    url: "https://poly.cam/capture/2917E164-71BC-49A2-B52B-B57EDE41B252?",
    copyrightHolder: "",
    page: 12,
    figure: 9,
  },
  {
    id: "camera",
    src: "/images/camera.png",
    alt: "Rendering of a security camera",
    title:
      "Rendering of a security camera, based on a GLTF object from 'https://poly.cam'",
    source: "https://poly.cam/capture/22949EAD-5E6F-4B55-8F4C-9376B508F20F?",
    author: "Maximilian Schmalenbach & metalmanprops",
    year: "2025",
    url: "https://poly.cam/capture/22949EAD-5E6F-4B55-8F4C-9376B508F20F?",
    copyrightHolder: "",
    page: 26,
    figure: 18,
  },
  {
    id: "computerAndHammer",
    src: "/images/mapped_computer_hammer.png",
    alt: "Rendering of a wooden hammer and a computer aligned in a circle",
    title:
      "Rendering of a wooden hammer and a computer aligned in a circle, based on a GLTF object from 'https://poly.cam'",
    source: "https://poly.cam/capture/BD126174-DEAA-4C3D-9071-86C3D657E0C6?",
    author: "Maximilian Schmalenbach & Pilki",
    year: "2025",
    url: "https://poly.cam/capture/BD126174-DEAA-4C3D-9071-86C3D657E0C6?",
    copyrightHolder: "",
    page: 34,
    figure: 20,
  },
  {
    id: "computerKidnappingInstitute",
    src: "/images/courant-institute.jpg",
    alt: "The Courant Institute, the math research center at N.Y.U., circa 1968.",
    title:
      "The Courant Institute, the math research center at N.Y.U., circa 1968.",
    source:
      "https://www.nytimes.com/2015/12/07/nyregion/the-mathematicians-who-ended-the-kidnapping-of-an-nyu-computer.html",
    author: "The New York Times",
    year: "2015",
    url: "https://www.nytimes.com/2015/12/07/nyregion/the-mathematicians-who-ended-the-kidnapping-of-an-nyu-computer.html",
    copyrightHolder: "The New York Times",
    page: 8,
    figure: 1,
  },
  {
    id: "computerKidnappingWeaverHall",
    src: "/images/outside-weaver-hall.jpg",
    alt: "Outside Warren Weaver Hall, the N.Y.U. building that housed the research computer, in May 1970.",
    title:
      "Outside Warren Weaver Hall, the N.Y.U. building that housed the research computer, in May 1970.",
    source:
      "https://www.nytimes.com/2015/12/07/nyregion/the-mathematicians-who-ended-the-kidnapping-of-an-nyu-computer.html",
    author: "The New York Times",
    year: "2015",
    url: "https://www.nytimes.com/2015/12/07/nyregion/the-mathematicians-who-ended-the-kidnapping-of-an-nyu-computer.html",
    copyrightHolder: "The New York Times",
    page: 8,
    figure: 2,
  },
  {
    id: "computerKidnappingExplosives",
    src: "/images/kidnapping-explosives.jpg",
    alt: "In 1970, student protesters seized an expensive computer and rigged it with improvised explosives.",
    title:
      "In 1970, student protesters seized an expensive computer and rigged it with improvised explosives.",
    source:
      "https://www.nytimes.com/2015/12/07/nyregion/the-mathematicians-who-ended-the-kidnapping-of-an-nyu-computer.html",
    author: "The New York Times",
    year: "2015",
    url: "https://www.nytimes.com/2015/12/07/nyregion/the-mathematicians-who-ended-the-kidnapping-of-an-nyu-computer.html",
    copyrightHolder: "The New York Times",
    page: 8,
    figure: 3,
  },
  {
    id: "aiCarProtest",
    src: "/images/ai-car-protest.jpg",
    alt: "Members of Safe Street Rebel place a cone on a self-driving Cruise car in San Francisco.",
    title:
      "Members of Safe Street Rebel place a cone on a self-driving Cruise car in San Francisco.",
    source:
      "https://www.npr.org/2023/08/26/1195695051/driverless-cars-san-francisco-waymo-cruise",
    author: "Josh Edelson/AFP via Getty Images",
    year: "2023",
    url: "https://www.npr.org/2023/08/26/1195695051/driverless-cars-san-francisco-waymo-cruise",
    copyrightHolder: "Josh Edelson/AFP via Getty Images",
    page: 8,
    figure: 5,
  },
  {
    id: "writerStrike",
    src: "/images/ai-writer-strike.jpg",
    alt: "Countless signs during the historic Hollywood strikes decried using AI. It's now creeping further into the entertainment industry.",
    title:
      "Countless signs during the historic Hollywood strikes decried using AI. It's now creeping further into the entertainment industry.",
    source: "https://www.bbc.com/news/articles/ce303x19dwgo",
    author: "BBC News",
    year: "2025",
    url: "https://www.bbc.com/news/articles/ce303x19dwgo",
    copyrightHolder: "BBC News",
    page: 8,
    figure: 6,
  },
  {
    id: "supercomputer",
    src: "/images/cdc-6600.png",
    alt: "The CDC 6600 is arguably the first supercomputer. It would later be kidnapped by students at N.Y.U.",
    title:
      "The CDC 6600 is arguably the first supercomputer. It would later be kidnapped by students at N.Y.U.",
    source: "https://www.bbc.com/news/articles/ce303x19dwgo",
    author: "BBC News",
    year: "2025",
    url: "https://www.bbc.com/news/articles/ce303x19dwgo",
    copyrightHolder: "BBC News",
    page: 8,
    figure: 4,
  },
  {
    id: "writerStrike2",
    src: "/images/ai-strike-2.jpg",
    alt: "Actor and SAG-AFTRA negotiator Frances Fisher, middle, raises her sign on a picket line outside Netflix studios on Tuesday, Sep. 26, 2023, in Los Angeles.",
    title:
      "Actor and SAG-AFTRA negotiator Frances Fisher, middle, raises her sign on a picket line outside Netflix studios on Tuesday, Sep. 26, 2023, in Los Angeles.",
    source:
      "https://apnews.com/article/hollywood-ai-strike-wga-artificial-intelligence-39ab72582c3a15f77510c9c30a45ffc8",
    author: "AP Photo Damian Dovarganes",
    year: "2023",
    url: "https://apnews.com/article/hollywood-ai-strike-wga-artificial-intelligence-39ab72582c3a15f77510c9c30a45ffc8",
    copyrightHolder: "AP Photo Damian Dovarganes",
    page: 8,
    figure: 7,
  },
  {
    id: "collageProposedProjectEntryZoom",
    src: "/images/collage-proposed-project-entry-zoom.png",
    alt: "Rendering of the proposed project, person A is denied entry, person B is allowed entry. Zoomed collage of various GLTF objects from 'https://poly.cam'",
    title:
      "Rendering of the proposed project, person A is denied entry, person B is allowed entry. Zoomed collage of various GLTF objects from 'https://poly.cam'",
    source: "https://poly.cam",
    author: "Maximilian Schmalenbach & poly.cam contributors",
    year: "2025",
    url: "https://poly.cam",
    copyrightHolder: "Maximilian Schmalenbach & poly.cam contributors",
    page: 32,
    figure: 19,
  },
];
